version: '3.8'

services:
      db:
        image: postgres:13.22-alpine
        container_name: db-1
        env_file:
          - .env
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        ports:
          - "5432:5432"

      web:
        build: .
        container_name: web-1
        env_file:
          - .env
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/code
        ports:
          - "8000:8000"
        depends_on:
          - db
volumes:
  postgres_data:

