---
# 1. ISTIO VIRTUAL SERVICE (New)

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: calculator-app-virtualservice
  namespace: sheela 
spec:
  hosts:
    - "basic_calculator.com" 
  gateways:
    - istio-system/ingress-gateway # Assumes Istio's default ingress gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: calculator-app-service
            port:
              number: 80 
---
# 2. POSTGRES SECRET 
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sheela
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: **********
  PGDATABASE: my_database
---
# 3. POSTGRES PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: sheela
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# 4. POSTGRES DEPLOYMENT 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: sheela
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
# 5. POSTGRES SERVICE 
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: sheela
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
# 6. CALCULATOR APP DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app-deployment
  namespace: sheela 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      imagePullSecrets:
      - name: acr-secret 
      
      # Init containers to wait for DB and run migrations (Corrected in previous step)
      initContainers:
        - name: wait-for-postgres
          image: busybox:latest
          command: ['sh', '-c', 'until nc -z $PGHOST $PGPORT; do echo waiting for postgres...; sleep 2; done;']
          env:
            - name: PGHOST
              value: postgres-service
            - name: PGPORT
              value: "5432"

        - name: migrate-db
          image: ngorongoro.azurecr.io/calculator_app:v1.7
          command: ['python', 'manage.py', 'migrate']
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PGDATABASE
            - name: PGHOST
              value: postgres-service
            - name: PGPORT
              value: "5432"
      
      # Main App Container
      containers:
        - name: calculator-app
          image: ngorongoro.azurecr.io/calculator_app:v1.7 
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PGDATABASE
            - name: PGHOST
              value: postgres-service
            - name: PGPORT
              value: "5432"
          ports:
            - containerPort: 8000
---
# 7. CALCULATOR APP SERVICE (Changed to ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service
  namespace: sheela
spec:
  selector:
    app: calculator-app
  type: ClusterIP # Changed from LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000 
